apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: hello-machine-deployment
  labels:
    app: hello-machine
    version: "0.2"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-machine
  template:
    metadata:
      labels:
        app: hello-machine
    spec:
      containers:
      - name: hello-machine
        image: nycdavid/hello-machine-id:latest
        ports:
        - containerPort: 3000
